proj1graph <- read.table("household_power_consumption.txt", sep=";", skip=66637, nrows=2880, stringsAsFactors=FALSE)
names(proj1graph) <- read.table("household_power_consumption.txt", sep=";", nrows=1, stringsAsFactors=FALSE)
Date_Time <- as.POSIXlt(paste(proj1graph$Date, proj1graph$Time), format="%d/%m/%Y %H:%M:%S")
proj1graph <- cbind(proj1graph, Date_Time<-as.POSIXlt(paste(proj1graph$Date, proj1graph$Time), format="%d/%m/%Y %H:%M:%S"))
proj1graph$Date <- as.Date(proj1graph$Date)
png("plot4.png")
par(mfrow=c(2,2))
with(proj1graph, {
  plot(Date_Time, Global_active_power, type="l", ylab="Global Active Power", xlab="")
  plot(Date_Time, Voltage, type="l", xlab="datetime")
  plot(Date_Time, Sub_metering_1, type="l", ylab="Energy Sub Metering", xlab="")
  lines(Date_Time, Sub_metering_2, type="l", col="red")
  lines(Date_Time, Sub_metering_3, type="l", col="blue")
  legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(Date_Time, Global_reactive_power, type="l", xlab="datetime")
})
dev.off()
