proj1graph <- read.table("household_power_consumption.txt", sep=";", skip=66637, nrows=2880, stringsAsFactors=FALSE)
names(proj1graph) <- read.table("household_power_consumption.txt", sep=";", nrows=1, stringsAsFactors=FALSE)
Date_Time <- as.POSIXlt(paste(proj1graph$Date, proj1graph$Time), format="%d/%m/%Y %H:%M:%S")
proj1graph <- cbind(proj1graph, Date_Time<-as.POSIXlt(paste(proj1graph$Date, proj1graph$Time), format="%d/%m/%Y %H:%M:%S"))
proj1graph$Date <- as.Date(proj1graph$Date)
png("plot3.png")
par(mar=c(3.1, 4.1, 4.1, 2.1))
plot(proj1graph$Date_Time, proj1graph$Sub_metering_1, type="l", ylab="Energy Sub Metering")
lines(proj1graph$Date_Time, proj1graph$Sub_metering_2, type="l", col="red")
lines(proj1graph$Date_Time, proj1graph$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
